from pathlib import Path

SCRAPER_DATA = Path("data")
IMG_DIR = SCRAPER_DATA / "images"

DEFAULT_CONCURRENCY = 6
REQUEST_DELAY = 1.5
TIMEOUT = 30
IMG_CONCURRENCY = 10
COOLDOWN_JITTER_MIN = 5
COOLDOWN_JITTER_MAX = 20
COOLDOWN_FALLBACK_MIN = 300
COOLDOWN_FALLBACK_MAX = 600
PAGE_WAIT_SHREDDIT_POST_MS = 2000
PAGE_WAIT_SHREDDIT_POST_FIRST_MS = 500
TABS_PER_BROWSER = 2
BROWSER_ROTATION_QUOTA = 50
BROWSER_COOLDOWN_FALLBACK_SECONDS = 60
BROWSER_WARMUP_URL = "https://www.reddit.com/"
BROWSER_WARMUP_TIMEOUT_MS = 5000
BROWSER_FIRST_LOAD_TIMEOUT_MS = 2000

SCRAPER_DATA.mkdir(parents=True, exist_ok=True)
